name: Deploy Frontend Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Build the site
        run: npm run build

      - name: Upload via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: dcism.org
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22077
          source: 'dist/'
          target: '~/directory.dcism.org/'
          overwrite: true
          strip_components: 1
